version: "3"
services:
  react-image:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev  
    ports:
      - "4000:3000"
    volumes:
      - "./src:/app/src"
    env_file:
      - "./.env"
